/*
File:   game_func_table_filling.cpp
Author: Taylor Robbins
Date:   03\05\2024
Description: 
	** Holds the function table filling implementation that is generated by PigGen
*/

#if PIGGEN
@FillGlobalFuncTable_Implementation
#else
#include "game_func_table_filling_cpp_0.h"
#endif
